### PR TITLE
Vale hifi pipeline

### PR DESCRIPTION
**Pull request by valegale**

### CODE REVIEW

**Comment by diegomics** [comment]
@tbrown91 let me know if you need help in testing this in order to merge it

**Comment by tbrown91** [comment]
Sure, I will test on a couple of species

**Comment by tbrown91** [comment]
I will use this thread for my comments and a ToDo list. I suspect I will be the one making the changes :)

**Comment by tbrown91** [comment]
It needs to be made explicit what the prerequisites are - this should be a much more prominent section of the README

e.g. pandas, snakemake, conda, yaml

**Comment by tbrown91** [comment]
mamba
snakemake version <8

**Pull request closed without merging**
