### PR TITLE
Use of smudge_pairs and kmc, instead meryl and hetkmers.

### PR DESCRIPTION
**Pull request by gkanogiannis**
This is an update of the `1.Genome_Profiling` snakemake pipeline for assembly.

The main change is that it uses `smudge_pairs` from [tbenavi1/KMC](https://github.com/tbenavi1/KMC) as it is suggested by [KamilSJaron/smudgeplot](https://github.com/KamilSJaron/smudgeplot).

This was not available for conda, so I had to create a new conda-forge recipe ([conda-forge/kmc_smudge_pairs-feedstock](https://github.com/conda-forge/kmc_smudge_pairs-feedstock)).
Conda-forge does not allow statically linked c++ packages, so I had to do some adjustments in the original code (edited code can be seen in [gkanogiannis/KMC](https://github.com/gkanogiannis/KMC).

Another change is that the limits L and U are dynamically calculated from the histogram and their values are used for filtering kmers for smudgeplot.

### CODE REVIEW

**Comment by mahajrod** [comment]
Could it handle data from mammalian sized genomes (2-4 Gbp) using reasonable amount of RAM (less than Tb) and time?...

**Comment by gkanogiannis** [comment]
> Could it handle data from mammalian sized genomes (2-4 Gbp) using reasonable amount of RAM (less than Tb) and time?...

I guess this is a question that would be best answered by the original [KMC](https://github.com/refresh-bio/KMC) authors.

But since KMC is a disk-based counter, I suspect it wouldn't have a RAM issue with any size of genome.

**Comment by mahajrod** [comment]
The question is more about smudge_pairs then KMC. Counter for sure could deal with big genomes... I asked because hetkmers in fact can't deal with such genomes (too much resources are necessary). If smudge_pairs also has the same issue, then it makes sense to turn off this part of the pipeline by default for compatibility with big genomes...

**Comment by gkanogiannis** [comment]
> The question is more about smudge_pairs then KMC. Counter for sure could deal with big genomes... I asked because hetkmers in fact can't deal with such genomes (too much resources are necessary). If smudge_pairs also has the same issue, then it makes sense to turn off this part of the pipeline by default for compatibility with big genomes...

Ok, now I got your question. Since I am not the original author of `KMC` with `smudge_pairs`, I wouldn't know for sure the answer. 
But since this is now easily available through conda-forge `conda install -c conda-forge kmc_smudge_pairs`, you could test it. Or alternatively you could share with me a link to a large genome and give it a try.

**Comment by tbrown91** [comment]
Merging for now and hoping the newer BGA24 version of smudgeplot will assist with these issues

**Pull request merged**
